chore: Updated build.

diff --git a/packages/cms/Dockerfile b/packages/cms/Dockerfile
--- a/packages/cms/Dockerfile
+++ b/packages/cms/Dockerfile
@@ -22,13 +22,14 @@ WORKDIR /app
 
 # Install dependencies based on the preferred package manager
 COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* bun.lock* ./
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
-  elif [ -f bun.lock ]; then bun install; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+RUN bun install
+# RUN \
+#   if [ -f yajn.lock ]; then yarn --frozen-lockfile; \
+#   elif [ -f package-lock.json ]; then npm ci; \
+#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+#   elif [ -f bun.lock ]; then bun install; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
 
 
 # Rebuild the source code only when needed
@@ -42,13 +43,14 @@ COPY . .
 # Uncomment the following line in case you want to disable telemetry during the build.
 # ENV NEXT_TELEMETRY_DISABLED 1
 
-RUN \
-  if [ -f yarn.lock ]; then yarn run build; \
-  elif [ -f package-lock.json ]; then npm run build; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
-  elif [ -f bun.lock ]; then bun run build; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+RUN bun run build
+# RUN \
+#   if [ -f yarn.lock ]; then yarn run build; \
+#   elif [ -f package-lock.json ]; then npm run build; \
+#   elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+#   elif [ -f bun.lock ]; then bun run build; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
 
 # Production image, copy all the files and run next
 FROM base AS runner
